- name: Deploy longhorn iscsi
  ansible.builtin.template:
    src: templates/longhorn-iscsi.j2
    dest: /var/lib/rancher/rke2/server/manifests/longhorn-iscsi.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  when: inventory_hostname == groups['servers'][0]

- name: Deploy longhorn nfs
  ansible.builtin.template:
    src: templates/longhorn-nfs.j2
    dest: /var/lib/rancher/rke2/server/manifests/longhorn-nfs.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  when: inventory_hostname == groups['servers'][0]

- name: Ensure longhorn-system namespace exists
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: longhorn-system
    kubeconfig: "{{ kubeconfig_path }}"
  delegate_to: localhost
  run_once: true

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"
    kubeconfig: "{{ kubeconfig_path }}"
  delegate_to: localhost
  run_once: true

- name: Deploy Longhorn using Helm
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    chart_version: v1.8.1
    values:
      defaultSettings.createDefaultDiskLabeledNodes: "true"
    wait: true
    kubeconfig: "{{ kubeconfig_path }}"
  delegate_to: localhost
  run_once: true

- name: Deploy longhorn manifest
  ansible.builtin.template:
    src: templates/longhorn-ingress-cert.j2
    dest: /var/lib/rancher/rke2/server/manifests/longhorn-ingress-cert.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  when: inventory_hostname == groups['servers'][0]
