- name: Deploy argocd-helm-chart.j2
  ansible.builtin.template:
    src: templates/argocd-helm-chart.j2
    dest: /var/lib/rancher/rke2/server/manifests/argocd-helm-chart.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  when: inventory_hostname == groups['servers'][0]

- name: Deploy argocd-ingress-route.j2
  ansible.builtin.template:
    src: templates/argocd-ingress-route.j2
    dest: /var/lib/rancher/rke2/server/manifests/argocd-ingress-route.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  when: inventory_hostname == groups['servers'][0]
  tags:
    - ssl
