- name: Create directory for RKE2 config
  ansible.builtin.file:
    path: "/etc/rancher/rke2"
    state: directory
    mode: "0644"

- name: Create systemd service file for RKE2 longhorn
  ansible.builtin.template:
    src: templates/rke2-agent.service.j2
    dest: /etc/systemd/system/rke2-agent.service
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname in groups['longhorn']

# Copy agent config to all agents - we need to change agent2 & 3 later with the token
- name: Deploy RKE2 longhorn Configuration
  ansible.builtin.template:
    src: templates/rke2-agent-config.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname in groups['longhorn']

# Check agents have restarted to pick up config
- name: Ensure RKE2 longhorn are enabled and running
  ansible.builtin.systemd:
    name: rke2-agent
    enabled: true
    state: restarted
    daemon_reload: true
