- name: Deploy kube-vip-rbac
  ansible.builtin.template:
    src: templates/kube-vip-rbac.j2
    dest: /var/lib/rancher/rke2/server/manifests/kube-vip-rbac.yaml
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == groups['servers'][0]

- name: Deploy kube-vip-config
  ansible.builtin.template:
    src: templates/kube-vip-config.j2
    dest: /var/lib/rancher/rke2/server/manifests/kube-vip-config.yaml
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == groups['servers'][0]

# For Service LoadBalancer type
- name: Deploy kube-vip-cloud-controller
  ansible.builtin.template:
    src: templates/kube-vip-cloud-controller.j2
    dest: /var/lib/rancher/rke2/server/manifests/kube-vip-cloud-controller.yaml
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == groups['servers'][0]

- name: Deploy rke2-traefik config
  ansible.builtin.template:
    src: templates/rke2-traefik-config.j2
    dest: /var/lib/rancher/rke2/server/manifests/rke2-traefik-config.yaml
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == groups['servers'][0]
