- name: Ensure cattle-system namespace exists
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: cattle-system
    kubeconfig: "{{ kubeconfig_path }}"
  delegate_to: localhost
  run_once: true

- name: Add latest chart repo
  kubernetes.core.helm_repository:
    name: rancher-latest
    repo_url: "https://releases.rancher.com/server-charts/latest"
    kubeconfig: "{{ kubeconfig_path }}"
  delegate_to: localhost
  run_once: true

- name: Deploy cattle-system using Helm
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-latest/rancher
    release_namespace: cattle-system
    set_values:
      - value: hostname=rancher.{{ ssl_local_domain }}
      - value: bootstrapPassword=admin
      - value: ingress.tls.source=secret
      - value: ingress.extraAnnotations.'cert-manager\.io/cluster-issuer'=cloudflare-clusterissuer
    wait: true
    kubeconfig: "{{ kubeconfig_path }}"
  delegate_to: localhost
  run_once: true

- name: Deploy rke2-cert-issuer.j2
  ansible.builtin.template:
    src: templates/rke2-cert-issuer.j2
    dest: /var/lib/rancher/rke2/server/manifests/rke2-cert-issuer.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
