#!/usr/bin/env python3

import json
import argparse


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate Ansible INI inventory from k8s_nodes.json and optional longhorn_nodes.json"
    )
    parser.add_argument("-j", "--json", required=True, help="Path to k8s_nodes.json")
    parser.add_argument("-l", "--longhorn", help="Optional path to longhorn_nodes.json")
    parser.add_argument(
        "-o", "--output", required=True, help="Path to output hosts.ini"
    )
    return parser.parse_args()


def load_nodes(json_file):
    with open(json_file) as f:
        return json.load(f)


def generate_inventory(k8s_nodes, longhorn_nodes=None):
    servers = []
    agents = []
    longhorn = []

    # Parse k8s nodes
    for name, info in k8s_nodes.items():
        ip = info["address"].split("/")[0]
        if info["role"] == "server":
            servers.append(f"{name} ansible_host={ip}")
        elif info["role"] == "agent":
            agents.append(f"{name} ansible_host={ip}")

    # Parse longhorn nodes
    if longhorn_nodes:
        for name, info in longhorn_nodes.items():
            ip = info["address"].split("/")[0]
            # agents.append(f"{name} ansible_host={ip}")  # also add to agents group
            longhorn.append(f"{name} ansible_host={ip}")  # and separate group

    # Generate INI-style inventory
    inventory = ["# Automatically generated by script", ""]

    inventory.append("[servers]")
    inventory.extend(servers)
    inventory.append("")

    inventory.append("[agents]")
    inventory.extend(agents)
    inventory.append("")

    if longhorn:
        inventory.append("[longhorn]")
        inventory.extend(longhorn)
        inventory.append("")

    inventory.append("[rke2:children]")
    inventory.append("servers")
    inventory.append("agents")
    if longhorn:
        inventory.append("longhorn")
    inventory.append("")

    return "\n".join(inventory)


def main():
    args = parse_args()
    k8s_nodes = load_nodes(args.json)
    longhorn_nodes = load_nodes(args.longhorn) if args.longhorn else None

    inventory_content = generate_inventory(k8s_nodes, longhorn_nodes)

    with open(args.output, "w") as f:
        f.write(inventory_content + "\n")

    print(f"✅ Inventory generated at {args.output}")


if __name__ == "__main__":
    main()
